package academy.digitalab.store.registry_service_mvn;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@EnableEurekaServer
@SpringBootApplication
public class RegistryServiceMvnApplication {

	public static void main(String[] args) {
		SpringApplication.run(RegistryServiceMvnApplication.class, args);
	}

}
